"use client";

import type { ReportResult } from "@/types/cxr";

interface ReportPanelProps {
  report: ReportResult;
}

export default function ReportPanel({ report }: ReportPanelProps) {
  const sections = report.sections || {};
  const hasSections = Object.keys(sections).length > 0;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-gray-700">Radiology Report</h3>
        <span className="text-xs text-gray-400">Generated by {report.model}</span>
      </div>

      {hasSections ? (
        <div className="space-y-3">
          {Object.entries(sections).map(([sectionName, content]) => (
            <div key={sectionName} className="rounded-lg border border-gray-200 overflow-hidden">
              <div className="bg-gray-50 px-3 py-2 border-b border-gray-200">
                <span className="text-xs font-bold text-gray-600 uppercase tracking-wide">
                  {sectionName}
                </span>
              </div>
              <div className="px-3 py-2">
                <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">
                  {content}
                </p>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-gray-50 rounded-lg p-4">
          <p className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed font-mono">
            {report.report}
          </p>
        </div>
      )}

      <p className="text-xs text-gray-400 italic">
        ⚠ AI-assisted report. Not a substitute for clinical judgment or board-certified radiologist review.
      </p>
    </div>
  );
}
